openapi: "3.0.0"
info:
  version: 1.0.0
  title: "medication plans api"
  description: "API of service example medication plans"
servers:
  - url: http://localhost:8002/v1

paths:
  /medicationcontainers:
    get:
      tags:
        - medications
      operationId: "getMedicationContainers"
      description: "returns all medication containers"
      responses:
        '200':
          description: list of medication containers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MedicationcontainerDTO"
                

  /medicationcontainers/findByCustomerId/{consumerId}:
    get:
      tags:
        - medications
      operationId: "findMedicationContainersByConsumer"
      description: "returns the medication containers of the parameterized medication consumer"
      parameters:
        - in: path
          name: consumerId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: list of medication containers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MedicationcontainerDTO"



  /medicationcontainers/{containerId}:
    get:
      tags:
        - medications
      operationId: "getMedicationContainer"
      description: "returns medication container with the parameterized containerId"
      parameters:
        - in: path
          name: containerId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: medication container
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MedicationcontainerDTO"

    put:
      tags:
        - medications
      operationId: "updateMedicationContainer"
      description: "updates the medication container with the parameterized containerId"
      parameters:
        - in: path
          name: containerId
          schema:
            type: string
          required: true
      requestBody:
        description: updated container
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationcontainerDTO'
      responses:
        '200':
          description: Updated

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    MedicationcontainerDTO:
      type: "object"
      properties:
        id:
          description: "technical id"
          type: "string"

        consumerId:
          description: "consumer id equals customer id from wawi"
          type: "string"

        consumerName:
          description: "surename of the medication consumer"
          type: "string"

        consumerFirstname:
          description: "firstname(s) of the medication consumer"
          type: "string"

        medications:
          description: "list of phonenumbers to communicate with the customer"
          type: array
          items:
            $ref: "#/components/schemas/MedicationDTO"


    MedicationDTO:
      type: "object"
      properties:
        id:
          description: "technial ID"
          type: "string"
        pharmacode:
          description: "pharmacode"
          type: "string"

        name:
          description: "name of the medication"
          type: "string"
