openapi: "3.0.0"
info:
  version: 1.0.0
  title: "customer api"
  description: "API of service example customer"
servers:
  - url: http://localhost:8002/v1
security:
  - bearerAuth: []

paths:
  /customers:
    get:
      tags:
        - customer
      operationId: "getCustomers"
      description: "returns all customers of the system"
      responses:
        '200':
          description: list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDTO"
                

  /customers/{customerId}:
    get:
      tags:
        - customer
      operationId: "getCustomer"
      description: "returns the customer with the parameterized customerId"
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: list of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDTO"

    put:
      tags:
        - customer
      operationId: "setCustomer"
      description: "updates the customer with the parameterized customerId"
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      requestBody:
        description: changed customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        '201':
          description: Created

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CustomerDTO:
      type: "object"
      properties:
        id:
          description: "technical id"
          type: "string"
        title:
          description: "mr / mrs. ...."
          type: "string"
        name:
          description: "surename of the customer"
          type: "string"
        firstname:
          description: "firstname(s) of the customer"
          type: "string"

        address:
          description: "the postal address of the customer"
          $ref: "#/components/schemas/AddressDTO"

        phones:
          description: "list of phonenumbers to communicate with the customer"
          type: array
          items:
            $ref: "#/components/schemas/PhoneDTO"


    AddressDTO:
      type: "object"
      properties:
        id:
          description: "technial ID"
          type: "string"
        street:
          description: "name of the street"
          type: "string"
        housenumber:
          description: "the housenumber of the customer (plus additional infos) (which level)"
          type: "string"
        postcode:
          description: "postal code"
          type: "string"
        city:
          description: "name of the city, auto added by postal code"
          type: "string"

    PhoneDTO:
      type: "object"
      properties:
        id:
          description: "technial ID"
          type: "string"
        number:
          description: "the phone number"
          type: "string"
        phonetype:
          description: "the phone type (mobile, work, private....)"
          type: "string"
