server:
  port: 8002

  ssl:
    key-store-type: PKCS12
    key-store: file:../keystore/commonmodule.p12
    key-store-password: commonmodule
    key-alias: commonmodule
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service
    username: cm
    password: cm
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: create

active-mq:
  broker-url: tcp://localhost:61616