version: "3.1" 
services:
  activemq: 
    image: rmohr/activemq
    ports: 
      - "61616:61616"
      - "8161:8161"

  postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=cm
      - POSTGRES_PASSWORD=cm
      - POSTGRES_DB=cm

    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cm"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: cm
      DB_USER: cm
      DB_SCHEMA: public
      DB_PASSWORD: cm
      KEYCLOAK_USER: cm
      KEYCLOAK_PASSWORD: cm
    ports:
      - 8080:8080
      - 9990:9990

#  adminer:
    #    image: adminer
    #restart: always
      #ports:
      #- 8080:8080

# rabbitmq:
#   image: bitnami/rabbitmq
#  ports:
#    - "15672:15672"
#  environment:
#    - RABBITMQ_DEFAULT_USER=cm
#    - RABBITMQ_DEFAULT_PASS=cm

networks:
  default:
    external:
      name: cm  # create a network with 'docker network create cm'
   
