openapi: "3.0.0"
info:
  version: 1.0.0
  title: "runtime api"
  description: "API which is provided by the module runtime itself"
servers:
  - url: http://localhost:8001/v1
security:
  - BasicAuth

paths:
  /modules/setup:
    post:
      tags:
        - module
      operationId: "installModules"
      description: "sets the modules up due to the description"
      requestBody:
        required: true
        description: modules descriptor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupModulesParamDTO"

      responses:
        '200':
          description: Installing modules succeded
  /modules/start:
    post:
      tags:
        - module
      operationId: "startModules"
      description: "starts the modules up due to the description"
      requestBody:
        required: true
        description: modules descriptor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupModulesParamDTO"

      responses:
        '200':
          description: Starting modules succeded

  /modules/stop:
    post:
      tags:
        - module
      operationId: "stopModules"
      description: "stops the modules up due to the description"
      requestBody:
        required: true
        description: modules descriptor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupModulesParamDTO"


      responses:
        '200':
          description: Stopping modules succeded
  /modules/status:
    post:
      tags:
        - module
      operationId: "statusModules"
      description: "gets the status of the modules up due to the description"
      requestBody:
        required: true
        description: modules descriptor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupModulesParamDTO"

      responses:
        '200':
          description: status of modules
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusModulesReturnDTO"


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    SetupModulesParamDTO:
      type: "object"
      properties:
        path:
          type: "string"
          description: "The path in which the common modules should be installed"
        descriptor: 
          type: "string"
          description: "The descriptor what should be installed"
        affectedModules:
          type: array
          description: "Comma separated list of affected modules, if empty all modules are affected"
          items:
            type: string
    StatusModulesReturnDTO:
      type: "object"
      properties:
        modules:
          type: array
          description: "The status object of the different common modules"
          items:
            $ref: "#/components/schemas/StatusModuleReturnDTO"
    StatusModuleReturnDTO:
      type: "object"
      properties:
        id:
          description: "The id of the common module"
          type: "string"
        running:
          description: "Boolean shows if the common module is running"
          type: "boolean"
        instanceId:
          description: "instanceID is the PID for jar based runtime or the container ID for docker based runtime"
          type: "string"
