openapi: "3.0.0"
info:
  version: 1.0.0
  title: "runtime api"
  description: "API which is provided by the module runtime itself"
servers:
  - url: http://localhost:8001
security:
  - BasicAuth

paths:
  /module/setup:
    post:
      tags:
        - module
      operationId: "installModules"
      description: "sets the modules up due to the description"
      requestBody:
        required: true
        description: modules descriptor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupModulesParamDTO"

      responses:
        '200':
          description: Ok
  /module/start:
    post:
      tags:
        - module
      operationId: "startModules"
      description: "starts the modules up due to the description"
      requestBody:
        required: true
        description: modules descriptor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupModulesParamDTO"

      responses:
        '200':
          description: Ok          
                
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    SetupModulesParamDTO:
      type: "object"
      properties:
        path:
          type: "string"
        descriptor: 
          type: "string"        
