openapi: "3.0.0"
info:
  version: 1.0.0
  title: "customer api"
  description: "API of service example customer"
servers:
  - url: http://localhost:8002
security:
  - BasicAuth

paths:
  /customer/findAll:
    get:
      tags:
        - customer
      operationId: "getCustomers"
      description: "returns all customers of the system"
      responses:
        '200':
          description: list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDTO"
                

  /customer/{customerId}:
    get:
      tags:
        - customer
      operationId: "getCustomer"
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: list of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDTO"

  /customer:
    put:
      tags:
        - customer
      operationId: "setCustomer"
      requestBody:
        description: changed customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        '201':
          description: Created

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    CustomerDTO:
      type: "object"
      properties:
        id:
          type: "string"
        title:
          type: "string"
        name:
          type: "string"
        firstname:
          type: "string"

        address:
          $ref: "#/components/schema/AddressDTO"

        phones:
          type: array
          items:
            $ref: "#/components/schema/PhoneDTO"


    AddressDTO:
      type: "object"
      properties:
        id:
          type: "string"
        address:
          type: "string"
        postcode:
          type: "string"
        city:
          type: "string"

    PhoneDTO:
      type: "object"
      properties:
        number:
          type: "string"
        phonetype:
          type: "string"