openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest project component"
  description: "Rest API for the mpm "
servers:
  - url: '{baseUrl}/v1'
security:
  - BasicAuth

paths:
  /emp/scanPlan:
    post:
      tags:
        - project
      operationId: "getProjects"
      description: "returns all projects the current user is authorized to see"
      responses:
        '200':
          description: list of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ElectronicMedPlanScanResponseDto"


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    ElectronicMedPlanScanResponseDto:
      type: "object"
      properties:
        medicationPlanId:
          type: "number"
        patientId:
          type: "number"

    ElectronicMedPlanScanRequestDto:
      type: "object"
      properties:
        inputXml:
          type: "string"